name: BasicChest
version: '${project.version}'
main: tk.dqmino.basicchest.BasicChest
api-version: 1.18
authors: [Dqmino]
description: A simple storage plugin opens the player chest with /chest, make a good storage system using the most performance cache method. Thanks to Redis, it can work as a cross server.
website: https://dqmino.tk

commands:
  chest:
    aliases: [playerchest, mychest]
    description: Ability to store items in a virtual chest never expiring or vanishing.
